version: "3.8"

services:
  database:
    container_name: database
    image: postgres:12.8
    restart: always
    environment:
      - POSTGRES_USER = pg
      - POSTGRES_PASSWORD = pass
      - POSTGRES_DB = crud
    ports:
      - 5432:5432
    networks:
      vpcbr:
        ipv4_address: 10.5.0.5
    volumes:
      - db:/var/lib/postgresql/data

networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1

volumes:
  db:

